# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_collection_message.proto

require 'google/protobuf'

require 'transaction_message_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("transaction_collection_message.proto", :syntax => :proto3) do
    add_message "TransactionCollectionMessage" do
      repeated :transactions, :message, 1, "TransactionMessage"
    end
  end
end

TransactionCollectionMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransactionCollectionMessage").msgclass
