# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("transaction_message.proto", :syntax => :proto3) do
    add_message "TransactionMessage" do
      optional :id, :int32, 1
      optional :description, :string, 2
      optional :kind, :string, 3
      optional :category_id, :int32, 4
    end
  end
end

TransactionMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransactionMessage").msgclass
